### ISSUE TITLE
BankId AutoStartToken

### ISSUE THREAD

**Issue by bdushi** [trustly/TrustlyAndroidSdk#3]
I have implemented the library and I am trying to make a deposit, using BankId as authentication provider, but when I start BankId, I need an autoStartToken, is there any way or EndPoint to get this.

**Comment by jennylarsson94** [comment]
@bdushi Hi and sorry for a very, very long overdue answer. I hope you've got an answer via some other channel meanwhile otherwise:

When integrating the Trustly SDK you should never need to care for the `autostarttoken` to initiate a session in Mobile BankID. The Trustly Checkout takes care of constructing the full redirect-url with all the params needed and it will be propagated to your application via the SDK (if integrated correctly).
